stages:
  - build
  - deploy
  - run

variables:
  JAR_NAME: "HMSystem-0.0.1-SNAPSHOT.jar"  # Modify as needed

before_script:
  - echo "Starting the build process"

build:
  stage: build
  script:
    # Ensure the working directory is set correctly
    - cd /builds/$CI_PROJECT_PATH/
    
    # Clean and build the project, skipping tests
    - mvn clean package -DskipTests
    
    # Verify the JAR file exists in the target directory
    - if [ -f target/*.jar ]; then echo "JAR file found"; else echo "JAR file not found"; exit 1; fi

deploy:
  stage: deploy
  script:
    # Move the generated JAR file to /mnt/vol1/
    - mv target/*.jar /mnt/vol1/

    # Verify the JAR file is in /mnt/vol1/
    - ls -l /mnt/vol1/
    
run:
  stage: run
  script:
    # Run the JAR file
    - java -jar /mnt/vol1/$JAR_NAME

