stages:
  - build
  - package
  - deploy

build_job:
  stage: build
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

package_job:
  stage: package
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 89.116.122.211 >> ~/.ssh/known_hosts
  script:
    - mv target/*.jar target/hms.jar
    - scp -i ~/.ssh/id_rsa target/hms.jar root@89.116.122.211:/mnt/vol1/HMS/
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "chown gitlab-runner:gitlab-runner /mnt/vol1/HMS/hms.jar"
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "ls -ltr /mnt/vol1/HMS/"
    - |
      ssh -i ~/.ssh/id_rsa root@89.116.122.211 '
      PIDS=$(ps aux | grep "[h]ms.jar" | awk "{print \$2}");
      if [ -n "$PIDS" ]; then
        echo "Stopping existing hms.jar processes: $PIDS";
        echo "$PIDS" | xargs -r kill || echo "Failed to kill one or more PIDs";
        sleep 5;
        echo "Processes stopped";
      else
        echo "No running hms.jar found";
      fi
      exit 0' || true
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "nohup java -jar /mnt/vol1/HMS/hms.jar > /mnt/vol1/HMS/hms.log 2>&1 &"
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "ps aux | grep '[h]ms.jar'"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
