stages:
  - build
  - deploy

# Use a Docker image that contains the required Maven and JDK
image: openjdk:17-slim

variables:
  JAR_NAME: "jarhotel.jar"  # Define the JAR file name

before_script:
  - apt-get update && apt-get install -y maven sshpass  # Install Maven and sshpass inside the container

build:
  stage: build
  script:
    # Step 1: Clean and build the JAR file
    - mvn clean package -DskipTests  # Build the JAR file

    # Step 2: Check if the JAR file is created and move it
    - ls -l target/  # List the contents of the target directory
    - mv target/*.jar /mnt/vol1/$JAR_NAME  # Move the JAR to /mnt/vol1

deploy:
  stage: deploy
  script:
    # Step 3: SSH into the server and run the JAR file
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@89.116.122.211 "
        nohup java -jar /mnt/vol1/$JAR_NAME > /mnt/vol1/app.log 2>&1 &
        echo 'Application started successfully in /mnt/vol1!'
      "
