stages:
  - build
  - package
  - deploy

variables:
# MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
# JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

before_script:
  - echo "Starting pipeline..."
  # - export JAVA_HOME=/usr/lib/jvm/java-17-corretto
  # - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - mvn --version

build:
  stage: build
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

package:
  stage: package
  image: maven:3.9.9-amazoncorretto-17
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 89.116.122.211 >> ~/.ssh/known_hosts
  script:
    - mv target/*.jar target/hms.jar
    - scp -i ~/.ssh/id_rsa target/*.jar root@89.116.122.211:/mnt/vol1/HMS/
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "chown gitlab-runner:gitlab-runner /mnt/vol1/HMS/hms.jar"
    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "ls -ltr /mnt/vol1/HMS/"
    # Start the new erp.jar
  #    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "nohup java -jar /mnt/vol1/IdCardBackend/idCard.jar > /mnt/vol1/IdCardBackend/idCard.log 2>&1 &"
  #    # Verify that the new erp.jar is running
  #    - ssh -i ~/.ssh/id_rsa root@89.116.122.211 "ps aux | grep '[e]rp.jar'"
  # only:
  #   - master
  rules:
    - if: $CI_COMMIT_BRANCH == "master"