stages:
  - deploy

deploy:
  stage: deploy
  image: openjdk:17-slim  # Use OpenJDK 17 image for deployment

  script:
    # Step 1: Install sshpass (if not available in the image)
    - apt-get update && apt-get install -y sshpass  

    # Step 2: Copy the JAR file to /mnt/vol1 on the server using SCP
    - sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no target/jarhotel.jar root@89.116.122.211:/mnt/vol1/jarhotel.jar

    # Step 3: SSH into the server and run the JAR file
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@89.116.122.211 "
        nohup java -jar /mnt/vol1/jarhotel.jar > /mnt/vol1/app.log 2>&1 & 
        echo 'Application started successfully in /mnt/vol1!' 
      "
